products:
  - id: subscription
    title: Subscription
    price: 20
    currency: "USD"
    recurring:
      every: 1
      unit: month
  - id: one-time
    title: Sample One-time purchase
    price: 20
    currency: "USD"
